[package]
name = "super_clicker"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.12", features = ["smol"] }
rdev = "0.5.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
dark-light = "1.0"
